version: '3'

services:
    postgres:
        image: postgres:9.6-alpine

    php:
        build: .
        restart: always
        volumes:
            - .:/var/www/html
        depends_on:
            - postgres
